Log:
  Level: none # Log level: none, error, warning, info, debug 
  AccessPath: # ./access.Log
  ErrorPath: # ./error.log
DnsConfigPath: # ./dns.json  Path to dns config
Nodes:
  -
    PanelType: "V2board" # Panel type: SSpanel
    ApiConfig:
      ApiHost: "https://123.com"
      ApiKey: "123"
      NodeID: 7
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request, Default is 5 sec
      EnableVless: false # Enable Vless for V2ray Type, Prefer remote configuration
      EnableXTLS: false # Enable XTLS for V2ray and Trojan， Prefer remote configuration
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Enable custom DNS config, Please ensure that you set the dns.json well
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "123" # Domain to cert
        CertFile: ./root/.acme.sh/123_ecc/123.cer # Provided if the CertMode is file
        KeyFile: ./root/.acme.sh/123_ecc/123.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@domain.com
        DNSEnv: # DNS ENV option used by DNS provider
        #  ALICLOUD_ACCESS_KEY: aaa
        #  ALICLOUD_SECRET_KEY: bbb
          CLOUDFLARE_EMAIL= test@domain.com \
          CLOUDFLARE_API_KEY=b9841238feb165a84330febba8a83208921177bffe733 \
          lego --email test@domain.com --dns cloudflare --domains domain.com run
  -
     PanelType: "V2board" # Panel type: SSpanel, V2board
     ApiConfig:
       ApiHost: "http://123.com"
       ApiKey: "123"
       NodeID: 7
       NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
       Timeout: 30 # Timeout for the api request
       EnableVless: false # Enable Vless for V2ray Type
       EnableXTLS: false # Enable XTLS for V2ray and Trojan
       SpeedLimit: 0 # Mbps, Local settings will replace remote settings
       DeviceLimit: 0 # Local settings will replace remote settings
     ControllerConfig:
       ListenIP: 0.0.0.0 # IP address you want to listen
       UpdatePeriodic: 10 # Time to update the nodeinfo, how many sec.
       EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
       CertConfig:
         CertMode: dns # Option about how to get certificate: none, file, http, dns
         CertDomain: "123" # Domain to cert
         CertFile: ./root/.acme.sh/123_ecc/123.cer # Provided if the CertMode is file
         KeyFile: ./root/.acme.sh/123_ecc/123.key
         Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
         Email: test@me.com
         DNSEnv: # DNS ENV option used by DNS provider
         #  ALICLOUD_ACCESS_KEY: aaa
         #  ALICLOUD_SECRET_KEY: bbb
           CLOUDFLARE_EMAIL= test@domain.com \
           CLOUDFLARE_API_KEY=b9841238feb165a84330febba8a83208921177bffe733 \
           lego --email test@domain.com --dns cloudflare --domains domain.com run
